---
- name: Deploy Proxy Server
  hosts: "proxy"
  become: True
  roles:
    - role: common
      tags: ['common']
    - role: proxy
      tags: ['proxy']
    - role: mtproto
      tags: ['proxy']
    - role: panel
      tags: ['vpn']
    # - role: wireguard
    #   tags: ['vpn']
