---
all:
  children:
    webservers:
      hosts:
        proxy:
          ansible_host: "{{ vps_ip }}" # your VPS IP
          ansible_user: "root"
          ansible_ssh_private_key_file: "~/.ssh/proxy"
