---
- name: Restart SSH
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Save iptables rules
  ansible.builtin.command: netfilter-persistent save

- name: Reboot a machine
  ansible.builtin.reboot:
